In [8]:
import pandas as pd

df = pd.read_csv("netflix_titles.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'netflix_titles.csv'

In [9]:
!unzip -l netflix_titles.csv.zip

unzip:  cannot find or open netflix_titles.csv.zip, netflix_titles.csv.zip.zip or netflix_titles.csv.zip.ZIP.

In [10]:
import os
print(os.listdir('/content'))

['.config', 'sample_data']

In [11]:
import os
print(os.listdir('/content'))

['.config', 'sample_data']

In [12]:
import pandas as pd

df = pd.read_csv("/content/netflix_titles.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/netflix_titles.csv'

In [13]:
import os
print(os.getcwd())

/content

In [14]:
import os

print(os.path.exists("/content/netflix_titles.csv"))

False

In [15]:
import pandas as pd

df = pd.read_csv("/netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [16]:
# Check dataset information
df.info()

# Check missing values
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [17]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [18]:
df["director"] = df["director"].fillna("Unknown")
df["cast"] = df["cast"].fillna("Not Available")
df["country"] = df["country"].fillna("Unknown")

In [19]:
df = df.dropna(subset=["date_added"])

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [22]:
print(df.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [23]:
df["type"] = df["type"].str.title()
df["country"] = df["country"].str.title().str.strip()

In [24]:
df["date_added"] = df["date_added"].str.strip()

df["date_added"] = pd.to_datetime(
    df["date_added"],
    format="mixed",
    errors="coerce"
)

df["date_added"] = df["date_added"].dt.strftime("%d-%m-%Y")

In [25]:
df[["title", "date_added"]].head()

                   title  date_added
0   Dick Johnson Is Dead  25-09-2021
1          Blood & Water  24-09-2021
2              Ganglands  24-09-2021
3  Jailbirds New Orleans  24-09-2021
4           Kota Factory  24-09-2021

In [26]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [27]:
df.to_csv("cleaned_netflix_dataset.csv", index=False)

print("Dataset cleaned successfully!")

Dataset cleaned successfully!

In [28]:
import os
print(os.listdir("/"))

['lib', 'mnt', 'proc', 'srv', 'opt', 'bin', 'var', 'boot', 'libx32', 'lib32', 'usr', 'tmp', 'run', 'etc', 'dev', 'home', 'media', 'lib64', 'sbin', 'root', 'sys', 'kaggle', 'netflix_titles.csv.zip', 'netflix_titles.csv', '.ipynb_checkpoints', 'content', '.dockerenv', 'tools', 'datalab', 'python-apt', 'python-apt.tar.xz']

In [29]:
import os
print(os.listdir("/content"))

['.config', 'cleaned_netflix_dataset.csv', 'sample_data']

In [30]:
from google.colab import files

files.download("/content/cleaned_netflix_dataset.csv")